DROP DATABASE IF EXISTS fetchAPI;

CREATE DATABASE fetchAPI;

USE fetchAPI;

CREATE TABLE Payers (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  payer VARCHAR(40) NOT NULL
);

CREATE TABLE Transactions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  payer VARCHAR(40),
  points INT,
  timestamp DATETIME,
  subBalance INT,
  trans_type VARCHAR(6),
  payerId INT,
  FOREIGN KEY (payerId) REFERENCES Payers(id)
);



